Upgraded to BouncyCastle 1.41.  Must use the "ext" provider, since the IDEA algorithm got removed from the regular provider.  Otherwise we would get the following exception:
org.bouncycastle.openpgp.PGPException: Exception creating cipher